[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-xid = "0.0.4"
unicode-properties = "0.1.1"

[dev-dependencies]
expect-test = "1.4.1"